--- 
user: root
group: root
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: ['/myapp/config.ru']
max_persistent_conns: 512
threaded: true
threadpool-size: 5
no-epoll: true
address: 0.0.0.0
port: 5000
tag: pgsc
